version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: indigenous-postgres-main
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: indigenous2024
      POSTGRES_DB: indigenous_platform
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - indigenous-net

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: indigenous-redis-main
    ports:
      - "6380:6379"
    networks:
      - indigenous-net

  # RFQ Service - THE CORE FEATURE
  rfq-service:
    build: ./indigenious-rfq-service
    container_name: indigenous-rfq
    ports:
      - "4001:4001"
    environment:
      PORT: 4001
      DATABASE_URL: postgresql://postgres:indigenous2024@postgres:5432/indigenous_platform
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - indigenous-net

  # Business Service
  business-service:
    build: ./indigenious-business-service
    container_name: indigenous-business
    ports:
      - "4002:4002"
    environment:
      PORT: 4002
      DATABASE_URL: postgresql://postgres:indigenous2024@postgres:5432/indigenous_platform
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - indigenous-net

  # Document Service
  document-service:
    build: ./indigenious-document-service
    container_name: indigenous-documents
    ports:
      - "4003:4003"
    environment:
      PORT: 4003
      DATABASE_URL: postgresql://postgres:indigenous2024@postgres:5432/indigenous_platform
      REDIS_URL: redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - indigenous-net

networks:
  indigenous-net:
    driver: bridge

volumes:
  postgres-data: