version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: indigenous-postgres
    environment:
      POSTGRES_DB: indigenous_platform
      POSTGRES_USER: indigenous_admin
      POSTGRES_PASSWORD: sacred_forest_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U indigenous_admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: indigenous-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Frontend
  frontend:
    build: ./indigenious-web-frontend
    container_name: indigenous-frontend
    ports:
      - "3100:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001
      NEXT_PUBLIC_DESIGN_SYSTEM_URL: http://localhost:3007
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
